spring.application.name=neurochat
server.port=8080

# ✅ USE ENV VARIABLES (SAFE)
openrouter.api.key=${OPENROUTER_API_KEY}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host=127.0.0.1
spring.redis.port=6379

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}